### ISSUE TITLE
Не отправляется почта при регистрации пользователей

### ISSUE THREAD

**Issue by icamys** [ulogin/ulogin-Wordpress#6]
Хотелось бы поблагодарить всех разработчиков за этот плагин.

При регистрации пользователя через Ваш плагин по сюжету должно отправляться уведомление администратору и пользователю об успешной регистрации на сайте, где пользователю оглашается его новый пароль.

Об этом свидетельствуют строчки из файла ulogin.php (588 - 590):

if (!is_wp_error($user_id) && $user_id > 0 && ($uLoginOptions['mail'] == 1))  {
    wp_new_user_notification($user_id, $user_pass);
}

Проблема возникает при обращении к $uLoginOptions['mail']. В настройках плагина такого свойства нет, поэтому при регистрации пользователя письмо с паролем пользователю не отправляется.

Для решения проблемы необходимо добавить в плагин эту настройку и вывести ее в панель администрирования.

**Comment by ipshenicyn** [comment]
Судя по коду плагина, проблема давно решена. 
Просим прощения за невнимательность и отсутствие реакции на проблему.
